# Generated by Django 3.2.7 on 2021-09-23 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_project_rates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
    ]
