# Generated by Django 3.2.7 on 2021-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20210925_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
